name: Build and Release

on:
  push:
    tags:
      - "v*" # Trigger on version tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Zip build folder
        run: cd dist && zip -r build.zip . && mv build.zip ../

      - name: Create release in target repository
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: build.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
